### PR TITLE
Ability to Pass hadoopConf Programmatically 

### PR DESCRIPTION
**Pull request by aravindr18**
- Added optional parameters fsConf to ParquetReader.Options and ParquetWriter.Options 

- Updated Readme

### CODE REVIEW

**Comment by aravindr18** [comment]
@mjakubowski84 Please let me know your thoughts

**Comment by mjakubowski84** [comment]
@aravindr18 and @mac01021 I just released your change. Sorry for doing it so late, I merged it on the weekend but forgot to release :)

**Comment by aravindr18** [comment]
@mjakubowski84 Thanks a lot! Appreciate all your help 👍

**Comment by mac01021** [comment]
Yes!  Thank you for releasing changes to this library so promptly!

**Pull request merged**
