### PR TITLE
Make parquet records mutable

### PR DESCRIPTION
**Pull request by mac01021**

### CODE REVIEW

**Comment by mjakubowski84** [comment]
Cool! I like it. I was thinking about pulling Iterable to ParquetRecord and make this type generic, but that can be too big change for your PR. Maybe just add small ScalaDoc to added functions as you want to use them publicly.

**Comment by mac01021** [comment]
So you would have the following? 

```
trait ParquetRecord[V] extends Iterable[V]

class RowParquetRecord extends ParquetRecord[Value]

class ListParquetRecord extends ParquetRecord[Value]

class MapParquetRecord extends ParquetRecord[(Value, Value)]

```

I'm not sure I see the value, but it's a small enough change.  I can do that if you like.

**Comment by mac01021** [comment]
It might also be nice for `ListParquetRecord` to have `map`, `filter`, etc on it directly, but I think I'm too lazy to figure out what the best way to do all that is.  Especially if you're going to change how these classes are designed in your next major release.

**Comment by mjakubowski84** [comment]
I meant exactly what you wrote. 
But it is optional for you, I just planned to do start the redesign with that :)
You can keep your original PR, just please add some ScalaDoc.
Maybe better move the change of schema name to another PR.
Then we can prepare 1.1.0 release - unless you have some other changes on mind.

**Comment by mac01021** [comment]
Sounds good.  I'll split up the PR and add some ScalaDoc tonight (American time).

In the meantime, if you have any thoughts about simple ways to improve my patch or add extra usability to these "internal" parquet records,  I could look at doing that tonight too.

**Comment by mac01021** [comment]
I thought I'd extend `mutable.Seq` and `mutable.Map`, since I'm implementing essentially those core ops anyway.  Then we can inherit all the functionality from those core collections like `mutable.Seq.transform`.  Do you think that's ok?

Don't merge this quite yet, though.  I'm trying to figure out the `IterableOps` stuff, so that the sequence operations `myListRecord.patch(...)` can return a `ListParquetRecord` instead of just an `Iterable[Value]`.

**Comment by mac01021** [comment]
This patch is now quite large.  I do not know if you will like it, but it now achieves the goal described in my previous comment.

I did not plan to add anywhere near this much code, but I followed Martin Odersky's example [here](https://docs.scala-lang.org/overviews/core/custom-collections.html#rna-sequences), and it seems this is how it is supposed to be done.  After this exercise, I am not a big fan of the new Scala 2.13 collections framework.

I used this code to do a little bit of ETL on some parquet files I have lying around, and it worked as expected.

Let me know what you think!

**Comment by mjakubowski84** [comment]
Great work!

**Comment by mjakubowski84** [comment]
Bad news, we have to revisit your PR again. You did a great job and that stuff might be quite useful. Unfortunately, this will work only with Scala 2.13. Parquet4s is cross-built back to Scala 2.11. When I look at download stats half of users still stick to v2.11. I tried Scala collection compatibility library https://github.com/scala/scala-library-compat. But that allows only to use Scala 2.13 - specific functions in older version. You don't get IndexedBuffer or StrictOptimizedSeqOps, etc.
All that mean that either we need to have separate implementation for each Scala version or we go back to your previous PR and keep things simple - with no fancy stuff :(

**Comment by mjakubowski84** [comment]
There's also a small issue with compatibility of the previous PR. I am working on it.
I forgot to add cross build check for PRs in circleci, my fault. I added it in my 1.1 release branch but it still not in master. My 1.1 grew too much ;/

**Pull request closed without merging**
